/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsSpan {
  start: number
  end: number
}
export interface JsError {
  code: number
  name: string
  span: JsSpan
}
export function check(path: string): Array<JsError>
